### ISSUE TITLE
Cant find the correct DXF for the classic maze tile

### ISSUE THREAD

**Issue by Talhahpatelia** [ukmars/maze-building#1]
I have included an image below of the tile that's DXF is missing from the resources folder. What I found in the resources folder was a tile that was similar but not exactly like the one below.

<img width="245" alt="image" src="https://github.com/ukmars/maze-building/assets/29210701/b943ca5a-1872-48d6-8eee-af51b5ade307">

Please may you include the DXF.

**Comment by micromouseonline** [comment]
Thank you for pointing that out. I have added two DXF files for the new maze design. I need to update the whle lot to bring it up to date

**Comment by Talhahpatelia** [comment]
Thank you.

I'll be closing this issue.
